# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppleTrendingHastags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100000)),
                ('source', models.CharField(max_length=100000)),
                ('author', models.CharField(max_length=100000)),
                ('name', models.CharField(max_length=100000)),
                ('time_zone', models.CharField(max_length=100000)),
                ('user_language', models.CharField(max_length=100000)),
                ('followers', models.CharField(max_length=100000)),
                ('user_description', models.CharField(max_length=100000)),
                ('geo_enabled', models.CharField(max_length=100000)),
                ('friends', models.CharField(max_length=100000)),
                ('retweets', models.CharField(max_length=100000)),
                ('location', models.CharField(max_length=100000)),
                ('user_id', models.CharField(max_length=100000)),
                ('coordinates', models.CharField(max_length=100000)),
                ('place', models.CharField(max_length=100000)),
                ('possible_senstive', models.CharField(max_length=100000)),
                ('status_created', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IphoneX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100000)),
                ('source', models.CharField(max_length=100000)),
                ('author', models.CharField(max_length=100000)),
                ('name', models.CharField(max_length=100000)),
                ('time_zone', models.CharField(max_length=100000)),
                ('user_language', models.CharField(max_length=100000)),
                ('followers', models.CharField(max_length=100000)),
                ('user_description', models.CharField(max_length=100000)),
                ('geo_enabled', models.CharField(max_length=100000)),
                ('friends', models.CharField(max_length=100000)),
                ('retweets', models.CharField(max_length=100000)),
                ('location', models.CharField(max_length=100000)),
                ('user_id', models.CharField(max_length=100000)),
                ('coordinates', models.CharField(max_length=100000)),
                ('place', models.CharField(max_length=100000)),
                ('possible_senstive', models.CharField(max_length=100000)),
                ('status_created', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
