# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appletrendinghastags',
            name='status_created',
            field=models.CharField(default='yo', max_length=100000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iphonex',
            name='status_created',
            field=models.CharField(default='yo', max_length=10000),
            preserve_default=False,
        ),
    ]
