# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20171106_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='appletrendinghastags',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='iphonex',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
